package com_piiottron

// list import classes
import com.piiottron.model.StateList;
import com.piiottron.model.DeviceEvent;

// default dialect for the semantic code will be MVEL
dialect "mvel"

// 100111 - Pi AI Tron IoT

rule "processID rule for device ID: 100111 - Pi AI Tron Device Module IoT-Jarvis"
	when
		$event : DeviceEvent( $eventId : id, $eventId == "100111" )
	then
		com.piiottron.model.StateList.getInstance().putState("processID", "com.JarvisPiAITron");
end

rule "Rules for device ID: 100111 - Pi AI Tron Device Module IoT-Jarvis"
 	no-loop
    when
    	// event used to change update Pi IoT Tron GPIO Light Module
		$event : DeviceEvent( $eventId : id, $eventId == "100111" )
    then
		System.out.println("Jarvis Pi IoT Tron Device Module > " + $event.getTextMessage());
end
