package com_environment

// list import classes
import com.piiottron.model.StateList;
import com.piiottron.model.DeviceEvent;

// default dialect for the semantic code will be JAVA
dialect "java"

rule "IoT Device Environment Conditions Readings"
	when
        $event : DeviceEvent( $eventId : id, $temp : temp, $ir_temp : ir_temp, $humidity : humidity, $mbar : mbar, $light : light )
	then
		String results = $event.getName() + " Temp:" + $temp + "  IR_Temp:" + $ir_temp + "  Humidity:" + $humidity + "  Mbar:" + $mbar + "  Light:" + $light
		System.out.println(results);
end

rule "IoT Device Event Readings"
	when
        $event : DeviceEvent( $eventId : id )
	then
		String results = $event.getName() + " Device Time " + $event.getDeviceTime() + " " + $event.getEvent();
		System.out.println(results);
end

//declare rule to fire when Temp is over 75
rule "Temp Raise alarm - Too Warm at Location"
	when
        $event : DeviceEvent( $eventId : id, $temp : temp, $temp > "75" )
	then
		System.out.println(">>Raise Temp Alarm " + $event.getName() + " Temperature:" + $temp);
end

rule "IoT Device Sent Text Message"
	when
        $event : DeviceEvent( $eventId : id, $textMessage : textMessage, $textMessage != null )
	then
		System.out.println($event.getName() + " Text Message: " + $textMessage);
end

rule "IoT Device Sent Alarm"
	when
        $event : DeviceEvent( $eventId : id, $alarm : alarm, $alarm != null )
	then
		System.out.println($event.getName() + " Sent Alarm: " + $alarm);
end