package com_gpsposition

// list import classes
import com.piiottron.model.StateList;
import com.piiottron.model.DeviceEvent;

// default dialect for the semantic code will be JAVA
dialect "java"

rule "GPS Device Distance"
	when
        $event : DeviceEvent( $eventId : id, $lat : lat, $lon : lon, $altitude : altitude, $distance : distance, $totalDistance : totalDistance )
	then
		System.out.println($event.getName() + " GPS Distance:" + $distance + " Total:" + $totalDistance + " Altitude:" + $altitude);
end

//declare rule to fire when Device speed is over 60
rule "GPS Device Speed Alert"
	when
        $event : DeviceEvent( $eventId : id, $lat : lat, $lon : lon, $altitude : altitude, $speed : speed, $speed > "60" )
	then
		System.out.println("!!! <<< " + $event.getName() + " GPS Device Speed Over 60.0 Alert lat:" + $lat + " lon:" + $lon + " speed:" + $speed + " >>> !!!");
end

rule "GPS Device Fix Information"
	when
        $event : DeviceEvent( $eventId : id, $serverTime : serverTime, $deviceTime : deviceTime, $fixTime : fixTime, $outdated : outdated, $valid : valid ) 
	then
		System.out.println($event.getName() + " GPS Fix on " + $deviceTime);
end

rule "GPS Device Address Location"
	when
        $event : DeviceEvent( $eventId : id, $address : address, $address != "null" )
	then
		System.out.println($event.getName() + " location " + $address);
end

rule "GPS Device Sent Text Message"
	when
        $event : DeviceEvent( $eventId : id, $textMessage : textMessage, $textMessage != null )
	then
		System.out.println($event.getName() + " Text Message: " + $textMessage);
end

rule "GPS Device Sent Alarm"
	when
        $event : DeviceEvent( $eventId : id, $alarm : alarm, $alarm != null )
	then
		System.out.println($event.getName() + " Sent Alarm: " + $alarm);
end

//declare rule to fire when Device in Motion
rule "GPS Device is in Motion"
    when
        $event : DeviceEvent( $eventId : id, $motion : motion, $motion == true )
    then
		System.out.println("GPS Device " + $event.getName() + " in Motion");
end
